server:
  port: 8091
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: booksharing
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/booksharing?useUnicode=true&characterEncoding=utf-8&&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  jpa:
    show-sql: true


